### ISSUE TITLE
Meta:  Please add short description to this repo

### ISSUE THREAD

**Issue by TPS** [maximeh/buildroot#3]
@maximeh That TL;DR summary _does_ help in locating this repo in internal/external search engines.  Just using __<kbd>**A simple, efficient and easy-to-use tool to generate embedded Linux systems through cross-compilation**</kbd>__ (from the 1st line of long description) should work perfectly.

**Comment by maximeh** [comment]
Thanks, done and added that it's only my WIP fork.
